artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/tproma/Multiple_Projects_Data/raw/main/learn-ai-bbc.zip
  local_data_file:  artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

 
